use crate::{
    generators::typescript::pascal_case,
    schema::{NuiSchema, TypeDefinition},
};

const HEADER: &str = "-- Generated by trek codegen. DO NOT EDIT DIRECTLY.\n";

pub fn generate_lua(schema: &NuiSchema) -> String {
    let mut out = format!("{HEADER}NUI = {{}}\n");
    for event in &schema.events {
        let fn_name = pascal_case(&event.name);
        let default_desc = format!("Emit '{}' event to UI", event.name);
        let doc = format_lua_doc(event.description.as_deref(), &default_desc);
        out.push_str(&format!(
            "\n{doc}\n---@param payload {}\nfunction NUI.emit{fn_name}(payload)\n    SendNUIMessage({{\n        action = \"{}\",\n        data = payload\n    }})\nend\n",
            lua_annotation(&event.payload),
            event.name
        ));
    }
    for endpoint in &schema.endpoints {
        let fn_name = pascal_case(&endpoint.name);
        let request = endpoint
            .request
            .as_ref()
            .map(lua_annotation)
            .unwrap_or_else(|| "nil".to_string());
        let default_desc = format!("Register callback handler for '{}'", endpoint.name);
        let doc = format_lua_doc(endpoint.description.as_deref(), &default_desc);
        out.push_str(&format!(
            "\n{doc}\n---@param handler fun(data: {}): {}\nfunction NUI.on{fn_name}(handler)\n    RegisterNuiCallback(\"{}\", function(data, cb)\n        local response = handler(data)\n        cb(response or {{}})\n    end)\nend\n",
            request,
            lua_annotation(&endpoint.response),
            endpoint.name
        ));
    }
    out
}

fn format_lua_doc(description: Option<&str>, default: &str) -> String {
    let text = description
        .filter(|s| !s.trim().is_empty())
        .unwrap_or(default);
    text.lines()
        .map(|line| format!("--- {line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn lua_annotation(ty: &TypeDefinition) -> String {
    match ty {
        TypeDefinition::Primitive(value) => value.trim_end_matches('?').to_string(),
        TypeDefinition::Array(items) => format!("{}[]", lua_annotation(&items[0])),
        TypeDefinition::Object(fields) => format!(
            "{{ {} }}",
            fields
                .iter()
                .map(|(name, ty)| format!("{name}: {}", lua_annotation(ty)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}
