use crate::schema::{EndpointType, EnumDefinition, NuiSchema, TypeDefinition};

const HEADER: &str = "// @ts-nocheck\n// Generated by trek codegen. DO NOT EDIT DIRECTLY.\n";

pub fn generate_typescript(schema: &NuiSchema) -> String {
    let mut imports = Vec::new();

    if schema
        .endpoints
        .iter()
        .any(|e| e.endpoint_type == EndpointType::Query)
    {
        imports.push("useNUIQuery");
    }
    if schema
        .endpoints
        .iter()
        .any(|e| e.endpoint_type == EndpointType::Mutation)
    {
        imports.push("useNUIMutation");
    }
    if !schema.events.is_empty() {
        imports.push("useNUIEvent");
    }
    if !schema.endpoints.is_empty() {
        imports.push("NUIQueryOptions");
    }

    let mut out = format!("{HEADER}\n");
    if !imports.is_empty() {
        out.push_str(&format!(
            "import {{ {} }} from \"@trekscripts/core/query\";\n",
            imports.join(", ")
        ));
    }

    for enum_def in &schema.enums {
        push_enum(&mut out, enum_def);
    }

    for event in &schema.events {
        push_ts_doc(&mut out, event.description.as_deref());
        push_interface(
            &mut out,
            &format!("{}Payload", pascal_case(&event.name)),
            &event.payload,
        );
    }
    for endpoint in &schema.endpoints {
        if let Some(request) = &endpoint.request {
            push_ts_doc(&mut out, endpoint.description.as_deref());
            push_interface(
                &mut out,
                &format!("{}Request", pascal_case(&endpoint.name)),
                request,
            );
        }
        push_ts_doc(&mut out, endpoint.description.as_deref());
        push_interface(
            &mut out,
            &format!("{}Response", pascal_case(&endpoint.name)),
            &endpoint.response,
        );
    }

    for event in &schema.events {
        let name = pascal_case(&event.name);
        push_ts_function(
            &mut out,
            event.description.as_deref(),
            &format!("use{name}Event"),
            &format!("handler: (data: {name}Payload) => void"),
            &format!("useNUIEvent<{name}Payload>(\"{}\", handler)", event.name),
        );
    }

    for endpoint in &schema.endpoints {
        let name = pascal_case(&endpoint.name);
        let request = if endpoint.request.is_some() {
            format!("{name}Request")
        } else {
            "void".to_string()
        };
        let (hook, suffix) = match endpoint.endpoint_type {
            EndpointType::Query => ("useNUIQuery", "Query"),
            EndpointType::Mutation => ("useNUIMutation", "Mutation"),
        };
        push_ts_function(
            &mut out,
            endpoint.description.as_deref(),
            &format!("use{name}{suffix}"),
            &format!("options?: NUIQueryOptions<{request}>"),
            &format!(
                "{hook}<{name}Response, {request}>(\"{}\", options)",
                endpoint.name
            ),
        );
    }

    out
}

fn push_enum(out: &mut String, enum_def: &EnumDefinition) {
    push_ts_doc(out, enum_def.description.as_deref());
    let enum_name = pascal_case(&enum_def.name);
    out.push_str(&format!("export enum {enum_name} {{\n"));
    for val in &enum_def.values {
        let member = enum_member_name(val);
        out.push_str(&format!("  {member} = \"{val}\",\n"));
    }
    out.push_str("}\n");
}

fn push_ts_function(
    out: &mut String,
    description: Option<&str>,
    fn_name: &str,
    params: &str,
    body_return: &str,
) {
    push_ts_doc(out, description);
    out.push_str(&format!(
        "export function {fn_name}({params}) {{\n  return {body_return};\n}}\n"
    ));
}

fn push_ts_doc(out: &mut String, description: Option<&str>) {
    out.push('\n');
    if let Some(desc) = description.filter(|s| !s.trim().is_empty()) {
        out.push_str("/**\n");
        for line in desc.lines() {
            out.push_str(&format!(" * {line}\n"));
        }
        out.push_str(" */\n");
    }
}

fn push_interface(out: &mut String, name: &str, ty: &TypeDefinition) {
    out.push_str(&format!("export interface {name} {{\n"));
    match ty {
        TypeDefinition::Object(fields) => {
            for (field, ty) in fields {
                push_ts_field(out, field, ty, 2);
            }
        }
        _ => push_ts_field(out, "value", ty, 2),
    }
    out.push_str("}\n");
}

fn push_ts_field(out: &mut String, field: &str, ty: &TypeDefinition, indent: usize) {
    out.push_str(&" ".repeat(indent));
    out.push_str(field);
    if ty.is_optional() {
        out.push('?');
    }
    out.push_str(&format!(": {};\n", ts_type(ty, indent)));
}

fn ts_type(ty: &TypeDefinition, indent: usize) -> String {
    match ty {
        TypeDefinition::Primitive(value) => {
            let base = value.trim_end_matches('?');
            match base {
                "string" => "string",
                "number" => "number",
                "boolean" => "boolean",
                custom => custom,
            }
            .to_string()
        }
        TypeDefinition::Array(items) => format!("Array<{}>", ts_type(&items[0], indent)),
        TypeDefinition::Object(fields) => {
            if fields.is_empty() {
                return "{}".to_string();
            }
            let next = indent + 2;
            let mut result = String::from("{\n");
            for (field, ty) in fields {
                result.push_str(&" ".repeat(next));
                result.push_str(field);
                if ty.is_optional() {
                    result.push('?');
                }
                result.push_str(&format!(": {};\n", ts_type(ty, next)));
            }
            result.push_str(&" ".repeat(indent));
            result.push('}');
            result
        }
    }
}

pub(super) fn pascal_case(value: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if capitalize {
                result.extend(character.to_uppercase());
                capitalize = false;
            } else {
                result.push(character);
            }
        } else {
            capitalize = true;
        }
    }
    result
}

pub(super) fn enum_member_name(value: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if capitalize {
                result.extend(character.to_uppercase());
                capitalize = false;
            } else {
                result.extend(character.to_lowercase());
            }
        } else {
            capitalize = true;
        }
    }
    if result.chars().next().map_or(false, |c| c.is_ascii_digit()) {
        result.insert(0, '_');
    }
    if result.is_empty() {
        result.push('_');
    }
    result
}
