use trek_fxmanifest::{Error, Game, Key, parse};

const FULL_MANIFEST: &str = r#"
# Generated by trek
fx_version 'cerulean'
game 'gta5'

-- resource metadata
author 'Trek Scripts'
description 'A test FiveM resource'
version '0.0.0'
lua54 'yes'

client_scripts {
    'config/share.lua',
    'src/client/client.lua',
}

server_scripts {
    "config/share.lua",
    "src/server/server.lua",
}

shared_script '@es_extended/imports.lua'

files {
    'config/client.lua',
    'config/server.lua',
}

dependencies { 'es_extended', 'qb-core' }
"#;

#[test]
fn parses_full_manifest() {
    let m = parse(FULL_MANIFEST).unwrap();

    assert_eq!(m.fx_version.as_deref(), Some("cerulean"));
    assert_eq!(m.game, Some(Game::Gta5));
    assert_eq!(m.version(), Some("0.0.0"));
    assert_eq!(m.description(), Some("A test FiveM resource"));
    assert_eq!(m.get(&Key::Author), Some("Trek Scripts"));
    assert_eq!(m.get(&Key::Lua54), Some("yes"));

    assert_eq!(
        m.client_scripts(),
        vec!["config/share.lua", "src/client/client.lua"]
    );
    assert_eq!(
        m.server_scripts(),
        vec!["config/share.lua", "src/server/server.lua"]
    );
    assert_eq!(m.shared_scripts(), vec!["@es_extended/imports.lua"]);
    assert_eq!(
        m.values(&Key::Files),
        vec!["config/client.lua", "config/server.lua"]
    );
    assert_eq!(m.values(&Key::Dependencies), vec!["es_extended", "qb-core"]);
}

#[test]
fn preserves_declaration_order() {
    let m = parse("version '1.0.0'\nauthor 'a'\ndescription 'd'\n").unwrap();
    let keys: Vec<&Key> = m.statements.iter().map(Statement::key).collect();
    assert_eq!(keys, vec![&Key::Version, &Key::Author, &Key::Description]);
}

use trek_fxmanifest::Statement;

#[test]
fn parses_function_call_syntax() {
    let m = parse("fx_version('cerulean')\nversion('1.2.3')\n").unwrap();
    assert_eq!(m.fx_version.as_deref(), Some("cerulean"));
    assert_eq!(m.version(), Some("1.2.3"));
}

#[test]
fn parses_assignment_syntax() {
    let m = parse("fx_version = \"cerulean\"\nversion = '2.0.0'\n").unwrap();
    assert_eq!(m.fx_version.as_deref(), Some("cerulean"));
    assert_eq!(m.version(), Some("2.0.0"));
}

#[test]
fn parses_bare_values() {
    let m = parse("game gta5\nlua54 yes\n").unwrap();
    assert_eq!(m.game, Some(Game::Gta5));
    assert_eq!(m.get(&Key::Lua54), Some("yes"));
}

#[test]
fn parses_unknown_keys_as_other() {
    let m = parse("this_is_a_map 'true'\n").unwrap();
    assert_eq!(m.get(&Key::Other("this_is_a_map".into())), Some("true"));
}

#[test]
fn parses_rdr3_game() {
    let m = parse("game 'rdr3'\n").unwrap();
    assert_eq!(m.game, Some(Game::Rdr3));
}

#[test]
fn empty_and_comment_only_manifests_are_empty() {
    let m = parse("").unwrap();
    assert!(m.statements.is_empty());

    let m = parse("-- nothing here\n\n-- more comments\n").unwrap();
    assert!(m.statements.is_empty());
}

#[test]
fn unterminated_string_is_lex_error() {
    let err = parse("version '1.0.0\n").unwrap_err();
    match err {
        Error::Lex(e) => {
            assert!(e.message.contains("unterminated string"), "{}", e.message);
            assert_eq!(e.line, 1);
        }
        other => panic!("expected lex error, got {other:?}"),
    }
}

#[test]
fn missing_value_is_parse_error() {
    let err = parse("version\n").unwrap_err();
    match err {
        Error::Parse(e) => {
            assert!(
                e.message.contains("'version' has no value"),
                "{}",
                e.message
            );
            assert_eq!((e.line, e.col), (1, 8));
        }
        other => panic!("expected parse error, got {other:?}"),
    }
}

#[test]
fn unclosed_table_is_parse_error() {
    let err = parse("client_scripts {\n  'a.lua',\n").unwrap_err();
    assert!(matches!(err, Error::Parse(_)));
}

#[test]
fn garbage_after_statement_is_parse_error() {
    let err = parse("version '1.0.0' author 'x'\n").unwrap_err();
    match err {
        Error::Parse(e) => assert!(e.message.contains("expected end of line")),
        other => panic!("expected parse error, got {other:?}"),
    }
}

#[test]
fn unexpected_character_is_lex_error() {
    let err = parse("version = ~\n").unwrap_err();
    assert!(matches!(err, Error::Lex(_)));
}
