use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};
use schemars::{JsonSchema, schema_for};
use serde::{Deserialize, Serialize};

const HEADER: &str = "// @ts-nocheck\n// Generated by trek codegen. DO NOT EDIT DIRECTLY.\n";
const STARTER_SCHEMA: &str = "# yaml-language-server: $schema=https://raw.githubusercontent.com/merzen-sh/trek-tools/refs/heads/main/trek-nui.schema.json\n\nversion: \"1.0\"\nresource: \"my_resource\"\nevents: []\nendpoints: []\n";

#[derive(Debug, Serialize, Deserialize, JsonSchema, Clone)]
#[serde(deny_unknown_fields)]
pub struct NuiSchema {
    pub version: String,
    pub resource: String,
    #[serde(default)]
    pub events: Vec<EventDefinition>,
    #[serde(default)]
    pub endpoints: Vec<EndpointDefinition>,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema, Clone)]
pub struct EventDefinition {
    pub name: String,
    pub description: Option<String>,
    pub payload: TypeDefinition,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema, Clone)]
pub struct EndpointDefinition {
    pub name: String,
    #[serde(rename = "type")]
    pub endpoint_type: EndpointType,
    pub description: Option<String>,
    #[serde(default)]
    pub request: Option<TypeDefinition>,
    pub response: TypeDefinition,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema, Clone, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum EndpointType {
    Query,
    Mutation,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema, Clone)]
#[serde(untagged)]
pub enum TypeDefinition {
    Primitive(String),
    Array(Vec<TypeDefinition>),
    Object(BTreeMap<String, TypeDefinition>),
}

pub fn run(schema_path: &Path, ts_out: &Path, lua_out: &Path, init_schema: bool) -> Result<()> {
    if init_schema {
        return initialize_schema(schema_path);
    }
    let input = fs::read_to_string(schema_path)
        .with_context(|| format!("failed to read schema '{}'", schema_path.display()))?;
    let schema: NuiSchema = serde_yml::from_str(&input)
        .with_context(|| format!("failed to parse schema '{}'", schema_path.display()))?;
    validate_schema(&schema)?;
    write_output(ts_out, &generate_typescript(&schema))?;
    write_output(lua_out, &generate_lua(&schema))?;
    println!(
        "Generated '{}' and '{}'.",
        ts_out.display(),
        lua_out.display()
    );
    Ok(())
}

fn initialize_schema(schema_path: &Path) -> Result<()> {
    if schema_path.exists() {
        bail!("schema '{}' already exists", schema_path.display());
    }
    let json_path = schema_path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join("trek-nui.schema.json");
    if json_path.exists() {
        bail!("JSON Schema '{}' already exists", json_path.display());
    }
    write_output(schema_path, STARTER_SCHEMA)?;
    let json = serde_json::to_string_pretty(&schema_for!(NuiSchema))?;
    write_output(&json_path, &format!("{json}\n"))?;
    println!(
        "Created '{}' and '{}'.",
        schema_path.display(),
        json_path.display()
    );
    Ok(())
}

fn write_output(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create output directory '{}'", parent.display()))?;
    }
    fs::write(path, contents).with_context(|| format!("failed to write '{}'", path.display()))
}

fn validate_schema(schema: &NuiSchema) -> Result<()> {
    if schema.version.trim().is_empty() || schema.resource.trim().is_empty() {
        bail!("schema version and resource must not be empty");
    }
    for event in &schema.events {
        validate_name(&event.name, "event")?;
        validate_type(&event.payload)?;
    }
    for endpoint in &schema.endpoints {
        validate_name(&endpoint.name, "endpoint")?;
        if let Some(request) = &endpoint.request {
            validate_type(request)?;
        }
        validate_type(&endpoint.response)?;
    }
    Ok(())
}

fn validate_name(name: &str, kind: &str) -> Result<()> {
    if name.trim().is_empty() {
        bail!("{kind} name must not be empty");
    }
    Ok(())
}

fn validate_type(ty: &TypeDefinition) -> Result<()> {
    match ty {
        TypeDefinition::Primitive(value) => match value.trim_end_matches('?') {
            "string" | "number" | "boolean" => Ok(()),
            other => bail!("unsupported type '{other}'; expected string, number, or boolean"),
        },
        TypeDefinition::Array(items) => {
            if items.len() != 1 {
                bail!("array types must contain exactly one item type");
            }
            validate_type(&items[0])
        }
        TypeDefinition::Object(fields) => fields.values().try_for_each(validate_type),
    }
}

pub fn generate_typescript(schema: &NuiSchema) -> String {
    let mut imports = Vec::new();

    if schema
        .endpoints
        .iter()
        .any(|e| e.endpoint_type == EndpointType::Query)
    {
        imports.push("useNUIQuery");
    }
    if schema
        .endpoints
        .iter()
        .any(|e| e.endpoint_type == EndpointType::Mutation)
    {
        imports.push("useNUIMutation");
    }
    if !schema.events.is_empty() {
        imports.push("useNUIEvent");
    }
    if !schema.endpoints.is_empty() {
        imports.push("NUIQueryOptions");
    }

    let mut out = format!("{HEADER}\n");
    if !imports.is_empty() {
        out.push_str(&format!(
            "import {{ {} }} from \"@trekscripts/core/query\";\n",
            imports.join(", ")
        ));
    }

    for event in &schema.events {
        push_ts_doc(&mut out, event.description.as_deref());
        push_interface(
            &mut out,
            &format!("{}Payload", pascal_case(&event.name)),
            &event.payload,
        );
    }
    for endpoint in &schema.endpoints {
        if let Some(request) = &endpoint.request {
            push_ts_doc(&mut out, endpoint.description.as_deref());
            push_interface(
                &mut out,
                &format!("{}Request", pascal_case(&endpoint.name)),
                request,
            );
        }
        push_ts_doc(&mut out, endpoint.description.as_deref());
        push_interface(
            &mut out,
            &format!("{}Response", pascal_case(&endpoint.name)),
            &endpoint.response,
        );
    }
    for event in &schema.events {
        let name = pascal_case(&event.name);
        push_ts_doc(&mut out, event.description.as_deref());
        out.push_str(&format!("export function use{name}Event(handler: (data: {name}Payload) => void) {{\n  return useNUIEvent<{name}Payload>(\"{}\", handler);\n}}\n", event.name));
    }
    for endpoint in &schema.endpoints {
        let name = pascal_case(&endpoint.name);
        let request = if endpoint.request.is_some() {
            format!("{name}Request")
        } else {
            "void".to_string()
        };
        let (hook, suffix) = match endpoint.endpoint_type {
            EndpointType::Query => ("useNUIQuery", "Query"),
            EndpointType::Mutation => ("useNUIMutation", "Mutation"),
        };
        push_ts_doc(&mut out, endpoint.description.as_deref());
        out.push_str(&format!("export function use{name}{suffix}(options?: NUIQueryOptions<{request}>) {{\n  return {hook}<{name}Response, {request}>(\"{}\", options);\n}}\n", endpoint.name));
    }
    out
}

fn push_ts_doc(out: &mut String, description: Option<&str>) {
    out.push('\n');
    if let Some(desc) = description.filter(|s| !s.trim().is_empty()) {
        out.push_str("/**\n");
        for line in desc.lines() {
            out.push_str(&format!(" * {line}\n"));
        }
        out.push_str(" */\n");
    }
}

fn push_interface(out: &mut String, name: &str, ty: &TypeDefinition) {
    out.push_str(&format!("export interface {name} {{\n"));
    match ty {
        TypeDefinition::Object(fields) => {
            for (field, ty) in fields {
                push_ts_field(out, field, ty, 2);
            }
        }
        _ => push_ts_field(out, "value", ty, 2),
    }
    out.push_str("}\n");
}

fn push_ts_field(out: &mut String, field: &str, ty: &TypeDefinition, indent: usize) {
    out.push_str(&" ".repeat(indent));
    out.push_str(field);
    if is_optional(ty) {
        out.push('?');
    }
    out.push_str(&format!(": {};\n", ts_type(ty, indent)));
}

fn ts_type(ty: &TypeDefinition, indent: usize) -> String {
    match ty {
        TypeDefinition::Primitive(value) => match value.trim_end_matches('?') {
            "string" => "string",
            "number" => "number",
            "boolean" => "boolean",
            _ => "unknown",
        }
        .to_string(),
        TypeDefinition::Array(items) => format!("Array<{}>", ts_type(&items[0], indent)),
        TypeDefinition::Object(fields) => {
            if fields.is_empty() {
                return "{}".to_string();
            }
            let next = indent + 2;
            let mut result = String::from("{\n");
            for (field, ty) in fields {
                result.push_str(&" ".repeat(next));
                result.push_str(field);
                if is_optional(ty) {
                    result.push('?');
                }
                result.push_str(&format!(": {};\n", ts_type(ty, next)));
            }
            result.push_str(&" ".repeat(indent));
            result.push('}');
            result
        }
    }
}

pub fn generate_lua(schema: &NuiSchema) -> String {
    let mut out = format!("-- {HEADER}\nNUI = {{}}\n");
    for event in &schema.events {
        let fn_name = pascal_case(&event.name);
        let default_desc = format!("Emit '{}' event to UI", event.name);
        let doc = format_lua_doc(event.description.as_deref(), &default_desc);
        out.push_str(&format!("\n{doc}\n---@param payload {}\nfunction NUI.emit{fn_name}(payload)\n    SendNUIMessage({{\n        action = \"{}\",\n        data = payload\n    }})\nend\n", lua_annotation(&event.payload), event.name));
    }
    for endpoint in &schema.endpoints {
        let fn_name = pascal_case(&endpoint.name);
        let request = endpoint
            .request
            .as_ref()
            .map(lua_annotation)
            .unwrap_or_else(|| "nil".to_string());
        let default_desc = format!("Register callback handler for '{}'", endpoint.name);
        let doc = format_lua_doc(endpoint.description.as_deref(), &default_desc);
        out.push_str(&format!("\n{doc}\n---@param handler fun(data: {}): {}\nfunction NUI.on{fn_name}(handler)\n    RegisterNuiCallback(\"{}\", function(data, cb)\n        local response = handler(data)\n        cb(response or {{}})\n    end)\nend\n", request, lua_annotation(&endpoint.response), endpoint.name));
    }
    out
}

fn format_lua_doc(description: Option<&str>, default: &str) -> String {
    let text = description
        .filter(|s| !s.trim().is_empty())
        .unwrap_or(default);
    text.lines()
        .map(|line| format!("--- {line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn lua_annotation(ty: &TypeDefinition) -> String {
    match ty {
        TypeDefinition::Primitive(value) => value.trim_end_matches('?').to_string(),
        TypeDefinition::Array(items) => format!("{}[]", lua_annotation(&items[0])),
        TypeDefinition::Object(fields) => format!(
            "{{ {} }}",
            fields
                .iter()
                .map(|(name, ty)| format!("{name}: {}", lua_annotation(ty)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn is_optional(ty: &TypeDefinition) -> bool {
    matches!(ty, TypeDefinition::Primitive(value) if value.ends_with('?'))
}

fn pascal_case(value: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if capitalize {
                result.extend(character.to_uppercase());
                capitalize = false;
            } else {
                result.push(character);
            }
        } else {
            capitalize = true;
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_imports_events_only() {
        let schema: NuiSchema = serde_yml::from_str(
            "version: \"1.0\"\nresource: test\nevents:\n  - name: speedUpdated\n    payload: { speed: number }\n",
        ).unwrap();

        let ts = generate_typescript(&schema);
        assert!(ts.contains("import { useNUIEvent } from \"@trekscripts/core/query\";"));
        assert!(!ts.contains("useNUIQuery"));
        assert!(!ts.contains("useNUIMutation"));
        assert!(!ts.contains("NUIQueryOptions"));
    }

    #[test]
    fn test_imports_query_only() {
        let schema: NuiSchema = serde_yml::from_str(
            "version: \"1.0\"\nresource: test\nendpoints:\n  - name: getInventory\n    type: query\n    response: { items: [string] }\n",
        ).unwrap();

        let ts = generate_typescript(&schema);
        assert!(
            ts.contains(
                "import { useNUIQuery, NUIQueryOptions } from \"@trekscripts/core/query\";"
            )
        );
        assert!(!ts.contains("useNUIMutation"));
        assert!(!ts.contains("useNUIEvent"));
    }

    #[test]
    fn test_imports_mutation_only() {
        let schema: NuiSchema = serde_yml::from_str(
            "version: \"1.0\"\nresource: test\nendpoints:\n  - name: useItem\n    type: mutation\n    request: { item: string }\n    response: { success: boolean }\n",
        ).unwrap();

        let ts = generate_typescript(&schema);
        assert!(ts.contains(
            "import { useNUIMutation, NUIQueryOptions } from \"@trekscripts/core/query\";"
        ));
        assert!(!ts.contains("useNUIQuery"));
        assert!(!ts.contains("useNUIEvent"));
    }

    #[test]
    fn test_imports_empty_schema() {
        let schema: NuiSchema = serde_yml::from_str("version: \"1.0\"\nresource: test\n").unwrap();

        let ts = generate_typescript(&schema);
        assert!(!ts.contains("import"));
        assert!(!ts.contains("@trekscripts/core/query"));
    }

    #[test]
    fn test_imports_all_combined() {
        let schema: NuiSchema = serde_yml::from_str(
            r#"
version: "1.0"
resource: test
events:
  - name: onAlert
    payload: { msg: string }
endpoints:
  - name: getData
    type: query
    response: { ok: boolean }
  - name: doAction
    type: mutation
    response: { ok: boolean }
"#,
        )
        .unwrap();

        let ts = generate_typescript(&schema);
        assert!(ts.contains("import { useNUIQuery, useNUIMutation, useNUIEvent, NUIQueryOptions } from \"@trekscripts/core/query\";"));
    }
}
