use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};
use schemars::{JsonSchema, schema_for};
use serde::{Deserialize, Serialize};

const HEADER: &str = "Generated by trek codegen. DO NOT EDIT DIRECTLY.";
const STARTER_SCHEMA: &str = "# yaml-language-server: $schema=trek-nui.schema.json\n\nversion: \"1.0\"\nresource: \"my_resource\"\nevents: []\nendpoints: []\n";

#[derive(Debug, Serialize, Deserialize, JsonSchema, Clone)]
#[serde(deny_unknown_fields)]
pub struct NuiSchema {
    pub version: String,
    pub resource: String,
    #[serde(default)]
    pub events: Vec<EventDefinition>,
    #[serde(default)]
    pub endpoints: Vec<EndpointDefinition>,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema, Clone)]
pub struct EventDefinition {
    pub name: String,
    pub description: Option<String>,
    pub payload: TypeDefinition,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema, Clone)]
pub struct EndpointDefinition {
    pub name: String,
    #[serde(rename = "type")]
    pub endpoint_type: EndpointType,
    pub description: Option<String>,
    #[serde(default)]
    pub request: Option<TypeDefinition>,
    pub response: TypeDefinition,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema, Clone, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum EndpointType {
    Query,
    Mutation,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema, Clone)]
#[serde(untagged)]
pub enum TypeDefinition {
    Primitive(String),
    Array(Vec<TypeDefinition>),
    Object(BTreeMap<String, TypeDefinition>),
}

pub fn run(schema_path: &Path, ts_out: &Path, lua_out: &Path, init_schema: bool) -> Result<()> {
    if init_schema {
        return initialize_schema(schema_path);
    }
    let input = fs::read_to_string(schema_path)
        .with_context(|| format!("failed to read schema '{}'", schema_path.display()))?;
    let schema: NuiSchema = serde_yml::from_str(&input)
        .with_context(|| format!("failed to parse schema '{}'", schema_path.display()))?;
    validate_schema(&schema)?;
    write_output(ts_out, &generate_typescript(&schema))?;
    write_output(lua_out, &generate_lua(&schema))?;
    println!(
        "Generated '{}' and '{}'.",
        ts_out.display(),
        lua_out.display()
    );
    Ok(())
}

fn initialize_schema(schema_path: &Path) -> Result<()> {
    if schema_path.exists() {
        bail!("schema '{}' already exists", schema_path.display());
    }
    let json_path = schema_path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join("trek-nui.schema.json");
    if json_path.exists() {
        bail!("JSON Schema '{}' already exists", json_path.display());
    }
    write_output(schema_path, STARTER_SCHEMA)?;
    let json = serde_json::to_string_pretty(&schema_for!(NuiSchema))?;
    write_output(&json_path, &format!("{json}\n"))?;
    println!(
        "Created '{}' and '{}'.",
        schema_path.display(),
        json_path.display()
    );
    Ok(())
}

fn write_output(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create output directory '{}'", parent.display()))?;
    }
    fs::write(path, contents).with_context(|| format!("failed to write '{}'", path.display()))
}

fn validate_schema(schema: &NuiSchema) -> Result<()> {
    if schema.version.trim().is_empty() || schema.resource.trim().is_empty() {
        bail!("schema version and resource must not be empty");
    }
    for event in &schema.events {
        validate_name(&event.name, "event")?;
        validate_type(&event.payload)?;
    }
    for endpoint in &schema.endpoints {
        validate_name(&endpoint.name, "endpoint")?;
        if let Some(request) = &endpoint.request {
            validate_type(request)?;
        }
        validate_type(&endpoint.response)?;
    }
    Ok(())
}

fn validate_name(name: &str, kind: &str) -> Result<()> {
    if name.trim().is_empty() {
        bail!("{kind} name must not be empty");
    }
    Ok(())
}

fn validate_type(ty: &TypeDefinition) -> Result<()> {
    match ty {
        TypeDefinition::Primitive(value) => match value.trim_end_matches('?') {
            "string" | "number" | "boolean" => Ok(()),
            other => bail!("unsupported type '{other}'; expected string, number, or boolean"),
        },
        TypeDefinition::Array(items) => {
            if items.len() != 1 {
                bail!("array types must contain exactly one item type");
            }
            validate_type(&items[0])
        }
        TypeDefinition::Object(fields) => fields.values().try_for_each(validate_type),
    }
}

pub fn generate_typescript(schema: &NuiSchema) -> String {
    let mut out = format!(
        "// {HEADER}\nimport {{ useNUIQuery, useNUIMutation, useNUIEvent, NUIQueryOptions }} from \"@trekscripts/core/query\";\n"
    );
    for event in &schema.events {
        push_interface(
            &mut out,
            &format!("{}Payload", pascal_case(&event.name)),
            &event.payload,
        );
    }
    for endpoint in &schema.endpoints {
        if let Some(request) = &endpoint.request {
            push_interface(
                &mut out,
                &format!("{}Request", pascal_case(&endpoint.name)),
                request,
            );
        }
        push_interface(
            &mut out,
            &format!("{}Response", pascal_case(&endpoint.name)),
            &endpoint.response,
        );
    }
    for event in &schema.events {
        let name = pascal_case(&event.name);
        out.push_str(&format!("\nexport function use{name}Event(handler: (data: {name}Payload) => void) {{\n  return useNUIEvent<{name}Payload>(\"{}\", handler);\n}}\n", event.name));
    }
    for endpoint in &schema.endpoints {
        let name = pascal_case(&endpoint.name);
        let request = if endpoint.request.is_some() {
            format!("{name}Request")
        } else {
            "void".to_string()
        };
        let (hook, suffix) = match endpoint.endpoint_type {
            EndpointType::Query => ("useNUIQuery", "Query"),
            EndpointType::Mutation => ("useNUIMutation", "Mutation"),
        };
        out.push_str(&format!("\nexport function use{name}{suffix}(options?: NUIQueryOptions<{request}>) {{\n  return {hook}<{name}Response, {request}>(\"{}\", options);\n}}\n", endpoint.name));
    }
    out
}

fn push_interface(out: &mut String, name: &str, ty: &TypeDefinition) {
    out.push_str(&format!("\nexport interface {name} {{\n"));
    match ty {
        TypeDefinition::Object(fields) => {
            for (field, ty) in fields {
                push_ts_field(out, field, ty, 2);
            }
        }
        _ => push_ts_field(out, "value", ty, 2),
    }
    out.push_str("}\n");
}

fn push_ts_field(out: &mut String, field: &str, ty: &TypeDefinition, indent: usize) {
    out.push_str(&" ".repeat(indent));
    out.push_str(field);
    if is_optional(ty) {
        out.push('?');
    }
    out.push_str(&format!(": {};\n", ts_type(ty, indent)));
}

fn ts_type(ty: &TypeDefinition, indent: usize) -> String {
    match ty {
        TypeDefinition::Primitive(value) => match value.trim_end_matches('?') {
            "string" => "string",
            "number" => "number",
            "boolean" => "boolean",
            _ => "unknown",
        }
        .to_string(),
        TypeDefinition::Array(items) => format!("Array<{}>", ts_type(&items[0], indent)),
        TypeDefinition::Object(fields) => {
            if fields.is_empty() {
                return "{}".to_string();
            }
            let next = indent + 2;
            let mut result = String::from("{\n");
            for (field, ty) in fields {
                result.push_str(&" ".repeat(next));
                result.push_str(field);
                if is_optional(ty) {
                    result.push('?');
                }
                result.push_str(&format!(": {};\n", ts_type(ty, next)));
            }
            result.push_str(&" ".repeat(indent));
            result.push('}');
            result
        }
    }
}

pub fn generate_lua(schema: &NuiSchema) -> String {
    let mut out = format!("-- {HEADER}\nNUI = {{}}\n");
    for event in &schema.events {
        let fn_name = pascal_case(&event.name);
        out.push_str(&format!("\n--- Emit '{}' event to UI\n---@param payload {}\nfunction NUI.emit{fn_name}(payload)\n    SendNUIMessage({{\n        action = \"{}\",\n        data = payload\n    }})\nend\n", event.name, lua_annotation(&event.payload), event.name));
    }
    for endpoint in &schema.endpoints {
        let fn_name = pascal_case(&endpoint.name);
        let request = endpoint
            .request
            .as_ref()
            .map(lua_annotation)
            .unwrap_or_else(|| "nil".to_string());
        out.push_str(&format!("\n--- Register callback handler for '{}'\n---@param handler fun(data: {}): {}\nfunction NUI.on{fn_name}(handler)\n    RegisterNuiCallback(\"{}\", function(data, cb)\n        local response = handler(data)\n        cb(response or {{}})\n    end)\nend\n", endpoint.name, request, lua_annotation(&endpoint.response), endpoint.name));
    }
    out
}

fn lua_annotation(ty: &TypeDefinition) -> String {
    match ty {
        TypeDefinition::Primitive(value) => value.trim_end_matches('?').to_string(),
        TypeDefinition::Array(items) => format!("{}[]", lua_annotation(&items[0])),
        TypeDefinition::Object(fields) => format!(
            "{{ {} }}",
            fields
                .iter()
                .map(|(name, ty)| format!("{name}: {}", lua_annotation(ty)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn is_optional(ty: &TypeDefinition) -> bool {
    matches!(ty, TypeDefinition::Primitive(value) if value.ends_with('?'))
}

fn pascal_case(value: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if capitalize {
                result.extend(character.to_uppercase());
                capitalize = false;
            } else {
                result.push(character);
            }
        } else {
            capitalize = true;
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn generates_example_contract() {
        let schema: NuiSchema = serde_yml::from_str("version: \"1.0\"\nresource: police_job\nevents:\n  - name: updateHealth\n    payload: { health: number }\nendpoints:\n  - name: getPlayers\n    type: query\n    request: { search: \"string?\" }\n    response:\n      players: [ { id: number, name: string } ]\n").unwrap();
        validate_schema(&schema).unwrap();
        let ts = generate_typescript(&schema);
        assert!(ts.contains("search?: string;"));
        assert!(ts.contains("useNUIQuery<GetPlayersResponse, GetPlayersRequest>"));
        assert!(ts.contains("players: Array<{"));
        let lua = generate_lua(&schema);
        assert!(lua.contains("function NUI.emitUpdateHealth"));
        assert!(lua.contains("function NUI.onGetPlayers"));
    }
}
