[package]
name = "trek"
version.workspace = true
edition.workspace = true

[[bin]]
name = "trek"
path = "src/main.rs"

[features]
default = ["generate"]
generate = ["dep:askama"]

[dependencies]
anyhow = { version = "1.0.104", default-features = false, features = ["std"] }
askama = { version = "0.16.0", default-features = false, features = ["derive", "alloc", "config"], optional = true }
clap = { version = "4.6.6", default-features = false, features = ["std", "derive", "help", "usage", "error-context","string","color"] }
console = "0.15"
sha2 = "0.10"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
trek-fxmanifest = { path = "../trek-fxmanifest" }

[dev-dependencies]
tempfile = "3"
